version: "3.9"

volumes:
  wireguard-admin-volume:
    name: wireguard-admin-config
  portainer-data-volume:
    name: portainer-data

networks:
  admin-network:
    name: pwn-admin
    ipam:
      driver: default
      config:
        - subnet: 12.2.0.0/24

services:
  agent:
    image: portainer/agent
    container_name: portainer-agent
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      admin-network:
        ipv4_address: 12.2.0.101

  portainer:
    image: portainer/portainer-ce
    container_name: portainer-ui
    restart: unless-stopped
    volumes:
      - portainer-data-volume:/data
    networks:
      admin-network:
        ipv4_address: 12.2.0.100

  wireguard-admin:
    image: linuxserver/wireguard
    container_name: wireguard-admin
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York # Change to your timezone.
      - SERVERPORT=7000 # 
      - PEERS=1 # Number of client profiles.
      - PEERDNS=1.1.1.1 # DNS when client is connected.
      - INTERNAL_SUBNET=12.6.0.0 # Subnet for all wireguard connections.
    volumes:
      - wireguard-admin-volume:/config
      - /lib/modules:/lib/modules
    ports:
      - "7000:51820/udp"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks:
      admin-network:
        ipv4_address: 12.2.0.3